# Generated by Django 2.1 on 2018-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('cbcl_6_18', 'cbcl_6_18')], default='cbcl_6_18', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
