# Generated by Django 2.1 on 2018-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('testing', '0002_auto_20180821_1311'), ('testing', '0003_test_test_type'), ('testing', '0004_auto_20180822_1303')]

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('CBCL_6_18', 'cbcl_6_18')], max_length=16),
        ),
    ]
