# Generated by Django 2.1 on 2018-09-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20180831_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('cbcl_6_18', 'cbcl_6_18'), ('cbcl_1_5', 'cbcl_1_5'), ('conners3_parent', 'conners3_parent'), ('tscyc', 'tscyc'), ('brief2', 'brief2'), ('srs2', 'srs2'), ('scared', 'scared'), ('tscc', 'tscc')], max_length=16),
        ),
    ]
