# Generated by Django 2.1.2 on 2019-04-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20181003_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('cbcl_6_18', 'CBCL 6-18'), ('cbcl_1_5', 'CBCL 1.5-5'), ('conners3_parent', 'Conners 3 - Parent'), ('conners3_self', 'Conners 3 - Self'), ('tscyc', 'TSCYC'), ('brief2', 'BRIEF2'), ('srs2', 'SRS2'), ('scared', 'SCARED'), ('tscc', 'TSCC'), ('asrs_6_18', 'ASRS 6-18')], max_length=16),
        ),
    ]
