# Generated by Django 2.2 on 2019-04-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_auto_20190411_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('cbcl_6_18', 'CBCL 6-18'), ('cbcl_1_5', 'CBCL 1.5-5'), ('conners3_parent', 'Conners 3 - Parent'), ('conners3_self', 'Conners 3 - Self'), ('tscyc', 'TSCYC'), ('brief2', 'BRIEF2'), ('briefp', 'BRIEF-P'), ('srs2', 'SRS2'), ('scared', 'SCARED'), ('tscc', 'TSCC'), ('asrs_6_18', 'ASRS 6-18'), ('asrs_2_5', 'ASRS 2-5'), ('masc2_self', 'MASC 2 - Self'), ('masc2_parent', 'MASC 2 - Parent')], max_length=16),
        ),
    ]
