# Generated by Django 2.2.5 on 2022-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_test_archived_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reverse_scoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='created_with_reverse_scoring',
            field=models.BooleanField(default=False),
        ),
    ]
