# Generated by Django 4.1.2 on 2022-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_auto_20220401_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='archived_items',
            field=models.JSONField(default=list),
        ),
    ]
