# Generated by Django 2.2 on 2019-07-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
